apiVersion: container-canary.nvidia.com/v1
kind: Validator
name: sagemaker-nim
description: Sagemaker-compatible NIM
documentation: https://github.com/NVIDIA/nim-deploy/tree/main/cloud-service-providers/aws/sagemaker
ports:
  - port: 8080
    protocol: TCP
checks:
  - name: uid
    description: 🆔 User ID is 0
    probe:
      exec:
        command:
          - /bin/sh
          - -c
          - "id | grep uid=0"
  - name: proxy-http-ping
    description: 🧭 Correctly routes /health
    probe:
      httpGet:
        path: /ping
        port: 8080
      failureThreshold: 30
  - name: proxy-http-invocations
    description: 🌏 Exposes an HTTP interface on port 8080 and path /invocations
    probe:
      httpGet:
        path: /invocations
        port: 8080
      failureThreshold: 30
  - name: core-http-health
    description: 🧭 NIM Correctly routes /v1/health/ready
    probe:
      httpGet:
        path: /v1/health/ready
        port: 8000
      failureThreshold: 30
  - name: core-http-chat
    description: 🧭 NIM Correctly routes /v1/chat/completions
    probe:
      httpGet:
        path: /v1/chat/completions
        port: 8000
      failureThreshold: 30
